-- Generated by LuaSTG Editor Sharp
-- Mod name: MyProject
_author = "ZOE"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
_LoadImageFromFile('image:'..'Marisa_Fight','Marisa_Fight.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Marisa_loser1','Marisa_loser1.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Marisa_loser2','Marisa_loser2.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Marisa_Normal','Marisa_Normal.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Reimu_Fight','Reimu_Fight.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Reimu_Normal','Reimu_Normal.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Reimu_smile','Reimu_smile.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Reimu_Angry','Reimu_Angry.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Rin_CloseEye','Rin_CloseEye.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Rin_Fight','Rin_Fight.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Rin_laugh','Rin_laugh.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Rin_normal','Rin_normal.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Rin_Fight2','Rin_Fight2.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'marisa_walknew','marisa_walknew.png',true,4,9,false,0)
_LoadImageFromFile('image:'..'reimu_walknew','reimu_walknew.png',true,4,8,false,0)
_LoadImageFromFile('image:'..'galaxy','galaxy.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'mask','mask.png',true,0,0,false,0)
LoadFX('fx:'..'boss_distortion','boss_distortion.hlsl')
LoadFX('fx:'..'alpha_mask','alpha_mask.hlsl')
_editor_class["spell_background1"]=Class(_spellcard_background)
_editor_class["spell_background1"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:mask",false,0,0,0,0,0,0,"",1,1,
        function(self)
            self.task={}
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
            PopRenderTarget("Mask")
            PostEffect('fx:alpha_mask','spell_test',6,'mul+alpha',{},{{"Mask",6},})
        end
    )
    _spellcard_background.AddLayer(self,"image:galaxy",false,0,0,0,0,0,0,"mul+alpha",1,1,
        function(self)
            self.task={}
            CreateRenderTarget("Mask")
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
            PopRenderTarget("")
            PushRenderTarget("Mask")
            RenderClear(0)
        end
    )
    _spellcard_background.AddLayer(self,"img_void",false,0,0,0,0,0,0,"",1,1,
        function(self)
            self.task={}
            CreateRenderTarget("spell_test")
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
            PushRenderTarget("spell_test")
        end
    )
end
_editor_class["laser_marisa"]=Class(laser)
_editor_class["laser_marisa"].init=function(self,_x,_y,ang)
    laser.init(self,COLOR_BLUE,_x,_y,0,0,0,0,15,0,0)
    
    self.rot=ang
    lasttask=task.New(self,function()
        self.layer=LAYER_ENEMY_BULLET-5
        last=New(_editor_class["laser_warning"],self.x,self.y,ang)
        laser._TurnHalfOn(self,0,true)
        do
            local _beg_l1=0 local l1=_beg_l1 local _end_l1=100 local _d_l1=(_end_l1-_beg_l1)/(60-1)
            local _beg_l2=0 local l2=_beg_l2 local _end_l2=400 local _d_l2=(_end_l2-_beg_l2)/(60-1)
            for _=1,60 do
                self.l1,self.l2=l1,l2
                task._Wait(1)
                l1=l1+_d_l1
                l2=l2+_d_l2
            end
        end
        task._Wait(60)
        laser._TurnOn(self,30,false,false)
        PlaySound("nep00",0.1,self.x/256,false)
        misc.ShakeScreen(240,3)
        do
            local _beg_d=0 local d=_beg_d local _end_d=150 local _d_d=(_end_d-_beg_d)/(60-1)
            for _=1,60 do
                self.w=d
                task._Wait(1)
                d=d+_d_d
            end
        end
        task._Wait(180)
        _del(self,true)
    end)
end
_editor_class["laser_warning"]=Class(laser)
_editor_class["laser_warning"].init=function(self,_x,_y,ang)
    laser.init(self,COLOR_BLUE,_x,_y,0,0,0,0,15,0,0)
    
    self.rot=ang
    lasttask=task.New(self,function()
        self.layer=LAYER_ENEMY_BULLET-5
        do
            local _beg_l1=0 local l1=_beg_l1 local _end_l1=100 local _d_l1=(_end_l1-_beg_l1)/(60-1)
            local _beg_l2=0 local l2=_beg_l2 local _end_l2=400 local _d_l2=(_end_l2-_beg_l2)/(60-1)
            for _=1,60 do
                self.l1,self.l2=l1,l2
                task._Wait(1)
                l1=l1+_d_l1
                l2=l2+_d_l2
            end
        end
        task._Wait(60)
        laser._TurnOn(self,0,false,false)
        self.colli=false
        do
            local _beg_d=0 local d=_beg_d local _end_d=280 local _d_d=(_end_d-_beg_d)/(60-1)
            for _=1,60 do
                self.w=d
                task._Wait(1)
                d=d+_d_d
            end
        end
        task._Wait(180)
        _del(self,true)
    end)
end
_editor_class["Mid_Spell_marisa"]=Class(_object)
_editor_class["Mid_Spell_marisa"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="image:Marisa_Fight"
    self.layer=LAYER_TOP+1
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.colli=false;
    self.x,self.y=256,-20;
    self.hscale,self.vscale=0.35,0.35;
    self.bound=false;
    lasttask=task.New(self,function()
        task.MoveTo(-75,0,60,MOVE_DECEL)
        task.MoveTo(-406,20,60,MOVE_ACCEL)
        _del(self,false)
    end)
end
_editor_class["Mid_Spell_reimu"]=Class(_object)
_editor_class["Mid_Spell_reimu"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="image:Reimu_Fight"
    self.layer=LAYER_TOP+1
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.colli=false;
    self.x,self.y=256,-20;
    self.hscale,self.vscale=0.35,0.35;
    self.bound=false;
    lasttask=task.New(self,function()
        task.MoveTo(-75,0,60,MOVE_DECEL)
        task.MoveTo(-406,20,60,MOVE_ACCEL)
        _del(self,false)
    end)
end
_editor_class["变色"]=Class(bullet)
_editor_class["变色"].init=function(self,_x,_y,A)
bullet.init(self,star_small,COLOR_YELLOW,true,true)
self.x,self.y=_x,_y
    SetV2(self,3,A,true,false)
    lasttask=task.New(self,function()
        task._Wait(30)
        ChangeBulletImage(self,star_small,COLOR_RED)
        task._Wait(30)
        ChangeBulletImage(self,star_small,COLOR_PURPLE)
        task._Wait(30)
        ChangeBulletImage(self,star_small,COLOR_CYAN)
        task._Wait(30)
        ChangeBulletImage(self,star_small,COLOR_GREEN)
        task._Wait(30)
        ChangeBulletImage(self,star_small,COLOR_YELLOW)
        task._Wait(30)
    end)
end
_editor_class["Marisa"]=Class(boss)
_editor_class["Marisa"].cards={}
_editor_class["Marisa"].name="Kirisame Marisa"
_editor_class["Marisa"].bgm=""
_editor_class["Marisa"]._bg=temple_background
_editor_class["Marisa"].difficulty="All"
table.insert(_editor_class["Marisa"].cards,boss.move.New(0,144,60,MOVE_NORMAL))
_editor_class["Marisa"].init=function(self,cards)
boss.init(self,240,384,_editor_class["Marisa"].name,cards,New(_editor_class["spell_background1"]),_editor_class["Marisa"].difficulty)
    self._wisys = BossWalkImageSystem(self)
    self._wisys:SetImage("marisa_walknew.png",4,9,{4,3,3,9},{1,1,1},6,16,16)
    boss.show_aura(self,true)
end
_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=true
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
        boss.dialog.sentence(self,"image:Rin_normal","left",[===[本工程为福大某无能大四学生的毕设演示。]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Marisa_Normal","right",[===[敢射击我就动了！！！]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Rin_normal","left",[===[哦？]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Marisa_Normal","right",[===[那个拿着二胡的，跑来这里是有什么要事吗？]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Rin_CloseEye","left",[===[嘛，自我介绍一下，我叫冴月 麟。]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Rin_laugh","left",[===[来这里是为了报变成未采用角色的一箭之仇......]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Marisa_Fight","right",[===[完全听不懂...算了,总之先打一架吧！]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Rin_Fight2","left",[===[好吧，要开始了哦！]===],nil,0.4,0.4)
        task._Wait(10)
    end)
end
table.insert(_editor_class["Marisa"].cards,_tmp_sc)
_tmp_sc=boss.card.New("这个是用于演示功能的啥都没有的符卡",2,5,60,1000,{0,0,0},false)
function _tmp_sc:before()
    last=New(_editor_class["Mid_Spell_marisa"],self.x,self.y)
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_NORMAL)
        task._Wait(60)
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Marisa"].cards,_tmp_sc)
table.insert(_sc_table,{"Marisa","这个是用于演示功能的啥都没有的符卡",_tmp_sc,#_editor_class["Marisa"].cards,false})
_tmp_sc=boss.card.New("",0,5,60,1000,{0,0,0},true)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        --[[ 风车弹
        ]]
        task.MoveTo(0,144,60,MOVE_NORMAL)
        do local a,_d_a=(0),(10) for _=1,_infinite do
            do local a1,_d_a1=(0),(360/8) for _=1,8 do
                last=New(_editor_class["变色"],self.x,self.y,a+a1)
            a1=a1+_d_a1 end end
            task._Wait(4)
        a=a+_d_a end end
    end)
    lasttask=task.New(self,function()
        task._Wait(120)
        for _=1,_infinite do
            task.MoveToPlayer(60,-64,64,100,144,48,32,8,16,MOVE_NORMAL,MOVE_RANDOM)
            task._Wait(90)
        end
        --[[ boss随机移动
        ]]
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Marisa"].cards,_tmp_sc)

_tmp_sc=boss.card.New("【魔炮】Gamma Ray Burst",3,8,80,1200,{0,0,0},false)
function _tmp_sc:before()
    last=New(_editor_class["Mid_Spell_marisa"],self.x,self.y)
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_DECEL)
        task._Wait(60)
        lasttask=task.New(self,function()
            for _=1,_infinite do
                boss.cast(self,120)
                last=New(_editor_class["laser_marisa"],self.x,self.y,Angle(self,player))
                task._Wait(360)
                task.MoveToPlayer(60,-96,96,112,144,30,80,8,16,MOVE_DECEL,MOVE_X_TOWARDS_PLAYER)
                task._Wait(60)
            end
        end)
        task._Wait(120)
        for _=1,_infinite do
            _create_bullet_group(star_small,COLOR_BLUE,self.x,self.y,6,0,1,1,ran:Float(0,360),360,false,2,true,true,0,false,self)
            _create_bullet_group(star_small,COLOR_GREEN,self.x,self.y,6,0,1,1,ran:Float(0,360),360,false,2,true,true,0,false,self)
            _create_bullet_group(star_small,COLOR_DEEP_PURPLE,self.x,self.y,6,0,1,1,ran:Float(0,360),360,false,2,true,true,0,false,self)
            _create_bullet_group(star_small,COLOR_RED,self.x,self.y,6,0,1,1,ran:Float(0,360),360,false,2,true,true,0,false,self)
            _create_bullet_group(star_small,COLOR_GOLDEN_YELLOW,self.x,self.y,6,0,2,2,ran:Float(0,360),360,false,2,true,true,0,false,self)
            PlaySound("tan01",0.1,self.x/256,false)
            task._Wait(25)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
    _drop_item(item_power_full,2,self.x,self.y)
end
_tmp_sc.perform=false
table.insert(_editor_class["Marisa"].cards,_tmp_sc)
table.insert(_sc_table,{"Marisa","【魔炮】Gamma Ray Burst",_tmp_sc,#_editor_class["Marisa"].cards,false})
_editor_class["Reimu"]=Class(boss)
_editor_class["Reimu"].cards={}
_editor_class["Reimu"].name="Hakure Reimu"
_editor_class["Reimu"].bgm=""
_editor_class["Reimu"]._bg=nil
_editor_class["Reimu"].difficulty="All"
_editor_class["Reimu"].init=function(self,cards)
boss.init(self,240,384,_editor_class["Reimu"].name,cards,New(_editor_class["spell_background1"]),_editor_class["Reimu"].difficulty)
    self._wisys = BossWalkImageSystem(self)
    self._wisys:SetImage("reimu_walknew.png",4,8,{4,3,3,8},{1,1,1},6,16,16)
end
_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=true
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
        boss.dialog.sentence(self,"image:Marisa_loser1","right",[===[什么嘛，还挺厉害的，那今天就到此为止...]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Reimu_Angry","right",[===[给我站住！！！]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Rin_laugh","left",[===[啊，来了来了！]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Marisa_loser2","right",[===[咦，灵、灵梦...（汗）]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Reimu_Angry","right",[===[多说无用！]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Reimu_smile","right",[===[魔理沙也好，那边那个搞破坏的也罢]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Reimu_smile","right",[===[全都要教训一顿才行！]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Reimu_Fight","right",[===[我要上咯！]===],nil,0.4,0.4)
        boss.dialog.sentence(self,"image:Rin_Fight2","left",[===[那就恭敬不如从命了！]===],nil,0.4,0.4)
    end)
end
table.insert(_editor_class["Reimu"].cards,_tmp_sc)
_tmp_sc=boss.card.New("",2,5,60,100,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_NORMAL)
        do local a1,_d_a1=(0),(3) for _=1,_infinite do
            do local x,_d_x,y,_d_y,a2,_d_a2=(ran:Float(-100,100)),(0),(ran:Float(-25,25)),(0),(0),(360/6) for _=1,6 do
                last=New(_straight,square,COLOR_RED,x,y,3,a1+a2,false,0,true,true,0,false,0,0,0,false)
            x=x+_d_x y=y+_d_y a2=a2+_d_a2 end end
            task._Wait(4)
        a1=a1+_d_a1 end end
        task._Wait(60)
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
    _drop_item(item_extend,1,self.x,self.y)
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Reimu"].cards,_tmp_sc)

_tmp_sc=boss.card.New("散装波粒",4,7,48,1200,{0,0,0},false)
function _tmp_sc:before()
    last=New(_editor_class["Mid_Spell_reimu"],self.x,self.y)
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_NORMAL)
        local i=(1)
        task._Wait(60)
        do local A0,_d_A0=(0),(127*2) for _=1,_infinite do
            do local R,_d_R,A1,_d_A1=(180),(-160/143),(A0),(7*i/64) for _=1,144 do
                do local A2,_d_A2=(A1^2),(360/8) for _=1,8 do
                    last=New(_straight,square,COLOR_RED,self.x+R*cos(A2),self.y+R*sin(A2),1,A2,false,0,true,true,0,false,0,0,0,false)
                A2=A2+_d_A2 end end
                task._Wait(4)
            R=R+_d_R A1=A1+_d_A1 end end
            i=-i
            task.MoveToPlayer(30,-96,96,112,144,16,32,8,16,MOVE_NORMAL,MOVE_X_TOWARDS_PLAYER)
            task._Wait(60)
        A0=A0+_d_A0 end end
    end)
end
function _tmp_sc:del()
    _drop_item(item_extend,1,self.x,self.y)
end
_tmp_sc.perform=false
table.insert(_editor_class["Reimu"].cards,_tmp_sc)
table.insert(_sc_table,{"Reimu","散装波粒",_tmp_sc,#_editor_class["Reimu"].cards,false})
_tmp_sc=boss.card.New("好消息，作者懒得做了，演示到此结束，求老师放过",2,5,60,800,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_NORMAL)
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Reimu"].cards,_tmp_sc)
table.insert(_sc_table,{"Reimu","好消息，作者懒得做了，演示到此结束，求老师放过",_tmp_sc,#_editor_class["Reimu"].cards,false})
stage.group.New('menu',{},"Extra",{lifeleft=2,power=400,faith=50000,bomb=2},true,1)
stage.group.AddStage('Extra','EXTRA@Extra',{lifeleft=8,power=400,faith=50000,bomb=8},true)
stage.group.DefStageFunc('EXTRA@Extra','init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty
    New(mask_fader,'open')
    if jstg then jstg.CreatePlayers() else New(_G[lstg.var.player_name]) end
    lasttask=task.New(self,function()
        New(winter_forest_background)
        LoadMusic('Reimu','THlib\\music\\xxrqm-4t1xb.ogg',75,0xc36e80/44100/4)
        LoadMusic('Marisa','THlib\\music\\6cqg9-3in5v.ogg',75,0xc36e80/44100/4)
        task._Wait(180)
        LoadMusicRecord("Marisa")
        _play_music("Marisa")
        local _boss_wait=true
        local _ref=New(_editor_class["Marisa"],_editor_class["Marisa"].cards)
        last=_ref
        if _boss_wait then while IsValid(_ref) do task.Wait() end end
        _stop_music()
        task._Wait(180)
        LoadMusicRecord("Reimu")
        _play_music("Reimu")
        local _boss_wait=true
        local _ref=New(_editor_class["Reimu"],_editor_class["Reimu"].cards)
        last=_ref
        if _boss_wait then while IsValid(_ref) do task.Wait() end end
        task._Wait(180)
    end)
    task.New(self,function()
        while coroutine.status(self.task[1])~='dead' do task.Wait() end
        stage.group.FinishReplay()
        New(mask_fader,'close')
        task.New(self,function()
            local _,bgm=EnumRes('bgm')
            for i=1,30 do
                for _,v in pairs(bgm) do
                    if GetMusicState(v)=='playing' then
                        SetBGMVolume(v,1-i/30)
                    end
                end
                task.Wait()
            end
        end)
        task.Wait(30)
        stage.group.FinishStage()
    end)
end)
