LoadTTF('boss_name', 'assets/font/VonwaonBitmap-16px.ttf', 20)
LoadTTF('sc_name', 'assets/font/VonwaonBitmap-16px.ttf', 26)
LoadTTF('sc_pr', 'assets/font/VonwaonBitmap-16px.ttf', 30)
LoadTTF('dialog', 'assets/font/VonwaonBitmap-16px.ttf', 30)
LoadTTF('menuttf', 'assets/font/VonwaonBitmap-16px.ttf', 20)

LoadFont('score', 'THlib/UI/font/Myfont_score.fnt', false)
LoadFont('item', 'THlib/UI/font/item.fnt', true)
LoadFont('menu', 'THlib/UI/font/Myfont.fnt', false)
LoadFont('bonus', 'THlib/UI/font/Myfont_score.fnt', true)
LoadFont('score1', 'THlib/UI/font/score1.fnt', false)
LoadFont('score2', 'THlib/UI/font/score2.fnt', false)
LoadFont('score3', 'THlib/UI/font/score3.fnt', false)
LoadFont('time', 'THlib/UI/font/score_new_score.fnt', true)
LoadFont('replay', 'THlib/UI/font/replay.fnt', false)
